Repository codetent/crypta, pull requests merged in 2024-01, with the labels that each got.

#21 Add doc starter
  .changes/header.tpl.md
  .changes/unreleased/Added-20240102-092219.yaml
  .changie.yaml
  .devcontainer/compose.yaml
  .devcontainer/devcontainer.json
  .github/pull_request_template.md
  .github/workflows/build.yml
  .github/workflows/dev-image.yml
  .github/workflows/gen-release-pr.yml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docker/Dockerfile
  docs/.gitignore
  docs/README.md
  docs/babel.config.js
  docs/docusaurus.config.ts
  docs/hack/cli/main.go
  docs/package-lock.json
  docs/package.json
  docs/pages/cli/_category_.json
  docs/pages/cli/crypta.md
  docs/pages/cli/crypta_daemon.md
  docs/pages/cli/crypta_get.md
  docs/pages/cli/crypta_set.md
  docs/pages/getting-started/_category_.json
  docs/pages/getting-started/installation.mdx
  docs/pages/intro.md
  docs/sidebars.ts
  docs/src/components/FeatureCard/index.tsx
  docs/src/components/FeatureCard/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/static/.nojekyll
  docs/static/img/check.svg
  docs/static/img/dolly.svg
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
  docs/static/img/plug.svg
  docs/tsconfig.json
Labels: documentation

#30 Hide verbose logging & remove usage string from application errors
  cmd/root.go
  pkg/daemon/client.go
  test/e2e/crypta_test.go
Labels: bug

#32 Add version flag
  cmd/root.go
  main.go
  test/e2e/crypta_test.go
Labels: feature

#33 Remove leading newline from password input
  pkg/cli/prompt.go
Labels: bug
